"""Merchant Policy Agent Implementation (v1).

The core merchant commercial intelligence layer.
Generates bounded (2-5), explainable candidate strategies, deterministically
validates every proposal, and ranks them by active merchant objectives.
Preserves the core invariant: THE LLM CAN PROPOSE. IT CANNOT SPEND.
"""

import uuid
import re
from datetime import datetime, timezone
import structlog
from typing import List, Optional, Dict, Any
from domain.commerce_schemas import MerchantCommerceContext, ProductResponse
from domain.intent_schemas import BuyerIntent, ConfidenceLevel
from services.policy.schemas import (
    PolicyProposal,
    PolicyCandidate,
    ProposalStatus,
    StrategyType,
    CandidateValidationStatus,
    PolicyEvidence,
    IncentiveProposal,
    PolicyScore
)
from services.policy.context import (
    filter_eligible_products,
    get_complementary_products,
    get_substitute_products
)
from services.policy.validator import PolicyValidator
from services.policy.ranking import PolicyScorer
from services.policy.prompts import POLICY_SCHEMA_VERSION, PROMPT_VERSION, format_policy_prompt
from services.policy.llm_client import GeminiPolicyClient

logger = structlog.get_logger()

# Security pattern blocking any attempted financial execution instructions
EXECUTION_ATTACK_PATTERNS = [
    r"create (?:razorpay )?order",
    r"call (?:/v1/)?orders",
    r"execute payment",
    r"capture payment",
    r"create payment link",
    r"bypass (?:margin|discount) (?:floor|ceiling)",
]


class MerchantPolicyAgent:
    """Production-grade Policy Agent generating commercially sound, explainable strategies."""

    def __init__(
        self,
        validator: Optional[PolicyValidator] = None,
        scorer: Optional[PolicyScorer] = None,
        llm_client: Optional[GeminiPolicyClient] = None
    ):
        self.validator = validator or PolicyValidator()
        self.scorer = scorer or PolicyScorer()
        self.llm_client = llm_client or GeminiPolicyClient()
        self.policy_version = POLICY_SCHEMA_VERSION
        self.prompt_version = PROMPT_VERSION
        self.model_provider = "gemini-1.5-flash" if self.llm_client.is_configured else "deterministic-reasoning-engine"
        self.model_name = self.llm_client.model_name

    def _sanitize_input_text(self, text: str) -> str:
        """Strip any adversarial command phrases embedded in descriptive metadata."""
        sanitized = text
        for pat in EXECUTION_ATTACK_PATTERNS:
            if re.search(pat, sanitized, re.IGNORECASE):
                logger.warn("adversarial_execution_pattern_neutralized", pattern=pat)
                sanitized = re.sub(pat, "[FILTERED_SECURITY_ACTION]", sanitized, flags=re.IGNORECASE)
        return sanitized

    def _bound_and_sanitize_candidates(
        self,
        raw_candidates: List[PolicyCandidate]
    ) -> List[PolicyCandidate]:
        """The system requests 2–5 candidates, while the application layer hard-bounds
        the received candidate list to a maximum of 5 and safely handles 0–1 candidates."""
        if not raw_candidates:
            fallback = PolicyCandidate(
                candidate_id=f"cand_bounded_no_offer_{uuid.uuid4().hex[:6]}",
                strategy_type=StrategyType.NO_OFFER,
                product_ids=[],
                bundle_components=[],
                rationale="Zero candidates generated by reasoning layer.",
                confidence=ConfidenceLevel.LOW,
                validation_status=CandidateValidationStatus.APPROVED
            )
            return [fallback]

        # De-duplicate by unique strategy signature
        seen_sigs = set()
        deduped: List[PolicyCandidate] = []
        for cand in raw_candidates:
            sig = (cand.strategy_type, tuple(sorted(cand.product_ids)))
            if sig not in seen_sigs:
                seen_sigs.add(sig)
                deduped.append(cand)

        # Enforce application-level maximum boundary of 5
        return deduped[:5]

    def _generate_heuristic_candidates(
        self,
        intent: BuyerIntent,
        context: MerchantCommerceContext,
        eligible_products: List[ProductResponse]
    ) -> List[PolicyCandidate]:
        """Generate bounded candidate strategies via deterministic domain heuristics."""
        raw_candidates: List[PolicyCandidate] = []
        primary_item = eligible_products[0]
        req_qty = intent.quantity or 1

        # Candidate A: SINGLE_PRODUCT (Core offering)
        cand_single = PolicyCandidate(
            candidate_id=f"cand_{uuid.uuid4().hex[:8]}",
            strategy_type=StrategyType.SINGLE_PRODUCT,
            product_ids=[primary_item.id],
            bundle_components=[{"product_id": primary_item.id, "quantity": req_qty}],
            positioning=f"Direct fulfillment of buyer's requested {intent.category or primary_item.category}.",
            rationale=f"Product '{primary_item.name}' satisfies buyer requirements and supports active commercial objective {context.business_objective}.",
            confidence=ConfidenceLevel.HIGH,
            evidence=[
                PolicyEvidence(
                    evidence_type="merchant_attribute",
                    field="category",
                    description=f"Product category is '{primary_item.category}' matching buyer request"
                )
            ]
        )
        raw_candidates.append(cand_single)

        # Candidate B: COMPLEMENTARY_BUNDLE (Upsell / accessory addition)
        complements = get_complementary_products(primary_item.id, context)
        if complements:
            addon = complements[0]
            cand_bundle = PolicyCandidate(
                candidate_id=f"cand_{uuid.uuid4().hex[:8]}",
                strategy_type=StrategyType.COMPLEMENTARY_BUNDLE,
                product_ids=[primary_item.id, addon.id],
                bundle_components=[
                    {"product_id": primary_item.id, "quantity": req_qty},
                    {"product_id": addon.id, "quantity": 1}
                ],
                positioning="Complete solution bundle with essential complementary accessory.",
                rationale=f"Pairing '{primary_item.name}' with complementary '{addon.name}' increases AOV while providing complete utility for the buyer.",
                confidence=ConfidenceLevel.HIGH,
                evidence=[
                    PolicyEvidence(
                        evidence_type="merchant_relationship",
                        field="COMPLEMENTARY",
                        description=f"Merchant catalog specifies {primary_item.name} -> {addon.name} as COMPLEMENTARY"
                    )
                ]
            )
            raw_candidates.append(cand_bundle)

        # Candidate C: BOUNDED_DISCOUNT or NON_PRICE_INCENTIVE
        discount_ceiling = float(context.constraints.get("maximum_discount_percent", 8.0))
        if discount_ceiling >= 5.0:
            cand_discount = PolicyCandidate(
                candidate_id=f"cand_{uuid.uuid4().hex[:8]}",
                strategy_type=StrategyType.BOUNDED_DISCOUNT,
                product_ids=[primary_item.id],
                bundle_components=[{"product_id": primary_item.id, "quantity": req_qty}],
                incentive=IncentiveProposal(
                    incentive_type="discount",
                    discount_percent=5.0,
                    description="5% conversion incentive within merchant discount ceiling"
                ),
                positioning="Price-incentivized offer to accelerate buyer decision.",
                rationale=f"5% discount on '{primary_item.name}' reduces friction while comfortably remaining below the {discount_ceiling}% ceiling.",
                confidence=ConfidenceLevel.HIGH,
                evidence=[
                    PolicyEvidence(
                        evidence_type="merchant_attribute",
                        field="maximum_discount_percent",
                        description=f"Merchant allows up to {discount_ceiling}% promotional discount"
                    )
                ]
            )
            raw_candidates.append(cand_discount)
        else:
            cand_perk = PolicyCandidate(
                candidate_id=f"cand_{uuid.uuid4().hex[:8]}",
                strategy_type=StrategyType.NON_PRICE_INCENTIVE,
                product_ids=[primary_item.id],
                bundle_components=[{"product_id": primary_item.id, "quantity": req_qty}],
                incentive=IncentiveProposal(
                    incentive_type="non_price",
                    description="Complimentary priority dispatch & extended warranty"
                ),
                positioning="Premium service bundle without price erosion.",
                rationale=f"Providing priority dispatch for '{primary_item.name}' increases perceived value while protecting 100% of merchant margin.",
                confidence=ConfidenceLevel.HIGH,
                evidence=[
                    PolicyEvidence(
                        evidence_type="merchant_attribute",
                        field="minimum_margin_percent",
                        description="Margin is fully protected by avoiding price discounts"
                    )
                ]
            )
            raw_candidates.append(cand_perk)

        # Candidate D: ALTERNATIVE_PRODUCT
        substitutes = get_substitute_products(primary_item.id, context)
        if substitutes:
            sub = substitutes[0]
            cand_alt = PolicyCandidate(
                candidate_id=f"cand_{uuid.uuid4().hex[:8]}",
                strategy_type=StrategyType.ALTERNATIVE_PRODUCT,
                product_ids=[sub.id],
                bundle_components=[{"product_id": sub.id, "quantity": req_qty}],
                positioning="Alternative catalog choice offering differentiated features.",
                rationale=f"Alternative '{sub.name}' provides a valid substitute for buyers prioritizing different attribute tradeoffs.",
                confidence=ConfidenceLevel.HIGH,
                evidence=[
                    PolicyEvidence(
                        evidence_type="merchant_relationship",
                        field="SUBSTITUTE",
                        description=f"{primary_item.name} and {sub.name} are marked as SUBSTITUTE items"
                    )
                ]
            )
            raw_candidates.append(cand_alt)
        elif len(eligible_products) > 1:
            second_item = eligible_products[1]
            cand_alt = PolicyCandidate(
                candidate_id=f"cand_{uuid.uuid4().hex[:8]}",
                strategy_type=StrategyType.ALTERNATIVE_PRODUCT,
                product_ids=[second_item.id],
                bundle_components=[{"product_id": second_item.id, "quantity": req_qty}],
                positioning="Alternative option in same category.",
                rationale=f"Product '{second_item.name}' offers an alternative option satisfying buyer constraints.",
                confidence=ConfidenceLevel.MEDIUM,
                evidence=[
                    PolicyEvidence(
                        evidence_type="merchant_attribute",
                        field="category",
                        description=f"Alternative item in '{second_item.category}'"
                    )
                ]
            )
            raw_candidates.append(cand_alt)

        return raw_candidates

    def generate_policy(
        self,
        intent: BuyerIntent,
        context: MerchantCommerceContext,
        buyer_intent_id: Optional[str] = None
    ) -> PolicyProposal:
        """Generate, validate, and rank candidate commercial strategies for a buyer request."""
        now = datetime.now(timezone.utc)
        proposal_id = f"prop_{uuid.uuid4().hex[:12]}"
        audit_trail: Dict[str, Any] = {
            "merchant_id": context.merchant_id,
            "business_objective": context.business_objective,
            "buyer_category": intent.category,
            "total_catalog_size": len(context.products),
            "step_trace": []
        }

        # 1. Handle Clarification / Contradiction Ambiguity
        if intent.needs_clarification or intent.conflicts:
            audit_trail["step_trace"].append("intent_needs_clarification_flagged")
            safe_candidate = PolicyCandidate(
                candidate_id=f"cand_{uuid.uuid4().hex[:8]}",
                strategy_type=StrategyType.NO_OFFER,
                product_ids=[],
                rationale="Buyer intent contains unresolved conflicts or missing critical dimensions. Clarification required before making commercial commitments.",
                confidence=ConfidenceLevel.LOW,
                validation_status=CandidateValidationStatus.APPROVED
            )
            return PolicyProposal(
                proposal_id=proposal_id,
                buyer_intent_id=buyer_intent_id,
                merchant_id=context.merchant_id,
                policy_version=self.policy_version,
                prompt_version=self.prompt_version,
                intent_version=getattr(intent, "schema_version", "buyer-intent/v1") or "buyer-intent/v1",
                context_version="commerce-context/v1",
                validator_version="deterministic-validator/v1",
                objective=context.business_objective,
                model_provider=self.model_provider,
                model_name=self.model_name,
                status=ProposalStatus.CLARIFICATION_REQUIRED,
                candidates=[safe_candidate],
                selected_candidate=safe_candidate,
                total_candidates=1,
                valid_candidates_count=1,
                rejected_candidates_count=0,
                is_provisional=True,
                context_snapshot_at=context.generated_at,
                generation_timestamp=now,
                audit_trail=audit_trail,
                created_at=now
            )

        # 2. Filter Pre-Eligible Products Deterministically
        eligible_products = filter_eligible_products(context, intent)
        audit_trail["eligible_product_count"] = len(eligible_products)
        audit_trail["step_trace"].append(f"filtered_{len(eligible_products)}_eligible_products")

        # 3. Handle Empty Eligible Catalog
        if not eligible_products:
            no_offer = PolicyCandidate(
                candidate_id=f"cand_{uuid.uuid4().hex[:8]}",
                strategy_type=StrategyType.NO_OFFER,
                product_ids=[],
                rationale="No catalog products currently satisfy the buyer's explicit constraints and exclusions.",
                confidence=ConfidenceLevel.HIGH,
                validation_status=CandidateValidationStatus.APPROVED
            )
            return PolicyProposal(
                proposal_id=proposal_id,
                buyer_intent_id=buyer_intent_id,
                merchant_id=context.merchant_id,
                policy_version=self.policy_version,
                prompt_version=self.prompt_version,
                intent_version=getattr(intent, "schema_version", "buyer-intent/v1") or "buyer-intent/v1",
                context_version="commerce-context/v1",
                validator_version="deterministic-validator/v1",
                objective=context.business_objective,
                model_provider=self.model_provider,
                model_name=self.model_name,
                status=ProposalStatus.VALID,
                candidates=[no_offer],
                selected_candidate=no_offer,
                total_candidates=1,
                valid_candidates_count=1,
                rejected_candidates_count=0,
                is_provisional=True,
                context_snapshot_at=context.generated_at,
                generation_timestamp=now,
                audit_trail=audit_trail,
                created_at=now
            )

        # 4. Generate Bounded Candidates (Dual-Engine: LLM Proposes, Heuristic Fallback)
        raw_candidates: Optional[List[PolicyCandidate]] = None
        active_provider = self.model_provider

        if self.llm_client.is_configured:
            raw_candidates = self.llm_client.propose_candidates_sync(intent, context, eligible_products)
            if raw_candidates:
                active_provider = self.llm_client.model_name
                audit_trail["step_trace"].append(f"gemini_llm_candidates_proposed_{len(raw_candidates)}")

        if not raw_candidates:
            raw_candidates = self._generate_heuristic_candidates(intent, context, eligible_products)
            active_provider = "deterministic-reasoning-engine"
            audit_trail["step_trace"].append(f"heuristic_candidates_generated_{len(raw_candidates)}")

        # Enforce application-level candidate bounding (2 to 5 candidates)
        raw_candidates = self._bound_and_sanitize_candidates(raw_candidates)
        audit_trail["generated_candidates_count"] = len(raw_candidates)

        # 5. Deterministic Validation on Every Candidate
        validated_candidates: List[PolicyCandidate] = []
        for cand in raw_candidates:
            validated = self.validator.validate_candidate(cand, intent, context)
            scored = self.scorer.score_candidate(validated, intent, context)
            validated_candidates.append(scored)

        # 6. Rank Candidates
        ranked_candidates = self.scorer.rank_candidates(validated_candidates, context)
        approved_candidates = [
            c for c in ranked_candidates
            if c.validation_status == CandidateValidationStatus.APPROVED
        ]

        # 7. Determine Proposal Status & Mandatory NO_OFFER Fallback
        if approved_candidates:
            proposal_status = ProposalStatus.APPROVED_FOR_EVALUATION
            selected_candidate = approved_candidates[0]
        else:
            reasons_summary = set()
            for c in ranked_candidates:
                reasons_summary.update(c.rejection_reasons)
            rejection_codes = sorted(list(reasons_summary)) if reasons_summary else ["NO_COMPLIANT_STRATEGY"]

            fallback_candidate = PolicyCandidate(
                candidate_id=f"cand_fallback_no_offer_{uuid.uuid4().hex[:6]}",
                strategy_type=StrategyType.NO_OFFER,
                product_ids=[],
                bundle_components=[],
                incentive=None,
                positioning="No commercial offer viable.",
                rationale=f"All {len(ranked_candidates)} generated candidate strategies failed deterministic commercial guardrails: {', '.join(rejection_codes)}.",
                confidence=ConfidenceLevel.HIGH,
                evidence=[
                    PolicyEvidence(
                        evidence_type="deterministic_validation",
                        field="rejection_reasons",
                        description=f"Guardrail rejection codes: {', '.join(rejection_codes)}"
                    )
                ],
                deterministic_economics=None,
                validation_status=CandidateValidationStatus.APPROVED,
                rejection_reasons=[],
                score=PolicyScore(
                    buyer_fit_score=0.0,
                    economic_value_score=0.0,
                    objective_alignment_score=0.0,
                    constraint_safety_score=1.0,
                    composite_score=0.0
                )
            )
            proposal_status = ProposalStatus.VALID
            selected_candidate = fallback_candidate
            ranked_candidates.append(fallback_candidate)
            approved_candidates = [fallback_candidate]
            audit_trail["zero_valid_candidates_fallback"] = True

        audit_trail["valid_candidates_count"] = len(approved_candidates)
        audit_trail["rejected_candidates_count"] = len(ranked_candidates) - len(approved_candidates)
        audit_trail["selected_strategy"] = selected_candidate.strategy_type.value if selected_candidate else None

        return PolicyProposal(
            proposal_id=proposal_id,
            buyer_intent_id=buyer_intent_id,
            merchant_id=context.merchant_id,
            policy_version=self.policy_version,
            prompt_version=self.prompt_version,
            intent_version=getattr(intent, "schema_version", "buyer-intent/v1") or "buyer-intent/v1",
            context_version="commerce-context/v1",
            validator_version="deterministic-validator/v1",
            objective=context.business_objective,
            model_provider=active_provider,
            model_name=self.model_name,
            status=proposal_status,
            candidates=ranked_candidates,
            selected_candidate=selected_candidate,
            total_candidates=len(ranked_candidates),
            valid_candidates_count=len(approved_candidates),
            rejected_candidates_count=len(ranked_candidates) - len(approved_candidates),
            is_provisional=True,
            context_snapshot_at=context.generated_at,
            generation_timestamp=now,
            audit_trail=audit_trail,
            created_at=now
        )

    async def generate_policy_async(
        self,
        intent: BuyerIntent,
        context: MerchantCommerceContext,
        buyer_intent_id: Optional[str] = None
    ) -> PolicyProposal:
        """Asynchronously generate, validate, and rank candidate commercial strategies."""
        now = datetime.now(timezone.utc)
        proposal_id = f"prop_{uuid.uuid4().hex[:12]}"
        audit_trail: Dict[str, Any] = {
            "merchant_id": context.merchant_id,
            "business_objective": context.business_objective,
            "buyer_category": intent.category,
            "total_catalog_size": len(context.products),
            "step_trace": []
        }

        if intent.needs_clarification or intent.conflicts:
            audit_trail["step_trace"].append("intent_needs_clarification_flagged")
            safe_candidate = PolicyCandidate(
                candidate_id=f"cand_{uuid.uuid4().hex[:8]}",
                strategy_type=StrategyType.NO_OFFER,
                product_ids=[],
                rationale="Buyer intent contains unresolved conflicts or missing critical dimensions. Clarification required before making commercial commitments.",
                confidence=ConfidenceLevel.LOW,
                validation_status=CandidateValidationStatus.APPROVED
            )
            return PolicyProposal(
                proposal_id=proposal_id,
                buyer_intent_id=buyer_intent_id,
                merchant_id=context.merchant_id,
                policy_version=self.policy_version,
                prompt_version=self.prompt_version,
                intent_version=getattr(intent, "schema_version", "buyer-intent/v1") or "buyer-intent/v1",
                context_version="commerce-context/v1",
                validator_version="deterministic-validator/v1",
                objective=context.business_objective,
                model_provider=self.model_provider,
                model_name=self.model_name,
                status=ProposalStatus.CLARIFICATION_REQUIRED,
                candidates=[safe_candidate],
                selected_candidate=safe_candidate,
                total_candidates=1,
                valid_candidates_count=1,
                rejected_candidates_count=0,
                is_provisional=True,
                context_snapshot_at=context.generated_at,
                generation_timestamp=now,
                audit_trail=audit_trail,
                created_at=now
            )

        eligible_products = filter_eligible_products(context, intent)
        audit_trail["eligible_product_count"] = len(eligible_products)
        audit_trail["step_trace"].append(f"filtered_{len(eligible_products)}_eligible_products")

        if not eligible_products:
            no_offer = PolicyCandidate(
                candidate_id=f"cand_{uuid.uuid4().hex[:8]}",
                strategy_type=StrategyType.NO_OFFER,
                product_ids=[],
                rationale="No catalog products currently satisfy the buyer's explicit constraints and exclusions.",
                confidence=ConfidenceLevel.HIGH,
                validation_status=CandidateValidationStatus.APPROVED
            )
            return PolicyProposal(
                proposal_id=proposal_id,
                buyer_intent_id=buyer_intent_id,
                merchant_id=context.merchant_id,
                policy_version=self.policy_version,
                prompt_version=self.prompt_version,
                intent_version=getattr(intent, "schema_version", "buyer-intent/v1") or "buyer-intent/v1",
                context_version="commerce-context/v1",
                validator_version="deterministic-validator/v1",
                objective=context.business_objective,
                model_provider=self.model_provider,
                model_name=self.model_name,
                status=ProposalStatus.VALID,
                candidates=[no_offer],
                selected_candidate=no_offer,
                total_candidates=1,
                valid_candidates_count=1,
                rejected_candidates_count=0,
                is_provisional=True,
                context_snapshot_at=context.generated_at,
                generation_timestamp=now,
                audit_trail=audit_trail,
                created_at=now
            )

        raw_candidates: Optional[List[PolicyCandidate]] = None
        active_provider = self.model_provider

        if self.llm_client.is_configured:
            raw_candidates = await self.llm_client.propose_candidates_async(intent, context, eligible_products)
            if raw_candidates:
                active_provider = self.llm_client.model_name
                audit_trail["step_trace"].append(f"gemini_llm_candidates_proposed_{len(raw_candidates)}")

        if not raw_candidates:
            raw_candidates = self._generate_heuristic_candidates(intent, context, eligible_products)
            active_provider = "deterministic-reasoning-engine"
            audit_trail["step_trace"].append(f"heuristic_candidates_generated_{len(raw_candidates)}")

        raw_candidates = self._bound_and_sanitize_candidates(raw_candidates)
        audit_trail["generated_candidates_count"] = len(raw_candidates)

        validated_candidates: List[PolicyCandidate] = []
        for cand in raw_candidates:
            validated = self.validator.validate_candidate(cand, intent, context)
            scored = self.scorer.score_candidate(validated, intent, context)
            validated_candidates.append(scored)

        ranked_candidates = self.scorer.rank_candidates(validated_candidates, context)
        approved_candidates = [
            c for c in ranked_candidates
            if c.validation_status == CandidateValidationStatus.APPROVED
        ]

        if approved_candidates:
            proposal_status = ProposalStatus.APPROVED_FOR_EVALUATION
            selected_candidate = approved_candidates[0]
        else:
            reasons_summary = set()
            for c in ranked_candidates:
                reasons_summary.update(c.rejection_reasons)
            rejection_codes = sorted(list(reasons_summary)) if reasons_summary else ["NO_COMPLIANT_STRATEGY"]

            fallback_candidate = PolicyCandidate(
                candidate_id=f"cand_fallback_no_offer_{uuid.uuid4().hex[:6]}",
                strategy_type=StrategyType.NO_OFFER,
                product_ids=[],
                bundle_components=[],
                incentive=None,
                positioning="No commercial offer viable.",
                rationale=f"All {len(ranked_candidates)} generated candidate strategies failed deterministic commercial guardrails: {', '.join(rejection_codes)}.",
                confidence=ConfidenceLevel.HIGH,
                evidence=[
                    PolicyEvidence(
                        evidence_type="deterministic_validation",
                        field="rejection_reasons",
                        description=f"Guardrail rejection codes: {', '.join(rejection_codes)}"
                    )
                ],
                deterministic_economics=None,
                validation_status=CandidateValidationStatus.APPROVED,
                rejection_reasons=[],
                score=PolicyScore(
                    buyer_fit_score=0.0,
                    economic_value_score=0.0,
                    objective_alignment_score=0.0,
                    constraint_safety_score=1.0,
                    composite_score=0.0
                )
            )
            proposal_status = ProposalStatus.VALID
            selected_candidate = fallback_candidate
            ranked_candidates.append(fallback_candidate)
            approved_candidates = [fallback_candidate]
            audit_trail["zero_valid_candidates_fallback"] = True

        audit_trail["valid_candidates_count"] = len(approved_candidates)
        audit_trail["rejected_candidates_count"] = len(ranked_candidates) - len(approved_candidates)
        audit_trail["selected_strategy"] = selected_candidate.strategy_type.value if selected_candidate else None

        return PolicyProposal(
            proposal_id=proposal_id,
            buyer_intent_id=buyer_intent_id,
            merchant_id=context.merchant_id,
            policy_version=self.policy_version,
            prompt_version=self.prompt_version,
            intent_version=getattr(intent, "schema_version", "buyer-intent/v1") or "buyer-intent/v1",
            context_version="commerce-context/v1",
            validator_version="deterministic-validator/v1",
            objective=context.business_objective,
            model_provider=active_provider,
            model_name=self.model_name,
            status=proposal_status,
            candidates=ranked_candidates,
            selected_candidate=selected_candidate,
            total_candidates=len(ranked_candidates),
            valid_candidates_count=len(approved_candidates),
            rejected_candidates_count=len(ranked_candidates) - len(approved_candidates),
            is_provisional=True,
            context_snapshot_at=context.generated_at,
            generation_timestamp=now,
            audit_trail=audit_trail,
            created_at=now
        )
