"""Typed Pydantic Schemas for Deterministic Learned Candidate Selection.

Contract: policy-selection/v1
Enforces strict schema validation, extra="forbid", and zero float currency.
Preserves explicit separation of concerns:
- Uses predicted_contribution_paise as primary ranking score.
- Exposes uncertainty as diagnostic metadata only; NEVER as an exploration mechanism.
- Enforces mandatory NO_OFFER baseline comparison.
"""

from typing import List, Optional, Dict, Any
from datetime import datetime
from pydantic import BaseModel, Field, ConfigDict
from domain.intent_schemas import BuyerIntent
from domain.commerce_schemas import MerchantCommerceContext
from services.policy.schemas import PolicyCandidate


SELECTION_SCHEMA_VERSION = "policy-selection/v1"


class CandidateSelectionScore(BaseModel):
    """Evaluation score and diagnostic metadata for a single policy candidate."""
    model_config = ConfigDict(extra="forbid")

    policy_id: str = Field(description="Unique candidate identifier")
    policy_version: str = Field(default="merchant-policy/v1", description="Policy contract version")
    predicted_contribution_paise: int = Field(description="Predicted net merchant economic contribution in integer paise")
    uncertainty: float = Field(description="Predictive standard deviation multiplier from Phase 8.4 model")
    rank: int = Field(ge=1, description="1-indexed rank within the evaluated candidate slate")
    is_baseline: bool = Field(default=False, description="True if this candidate represents the NO_OFFER baseline")
    selection_eligible: bool = Field(default=True, description="True if candidate passed structural validity checks")
    exclusion_reason: Optional[str] = Field(default=None, description="Reason candidate was excluded from selection if ineligible")


class PolicySelectionRequest(BaseModel):
    """Input payload for deterministic learned candidate selection."""
    model_config = ConfigDict(extra="forbid")

    merchant_id: str = Field(min_length=1, max_length=64, description="Merchant tenant ID")
    opportunity_id: str = Field(min_length=1, max_length=128, description="Canonical buyer shopping opportunity identity")
    buyer_context_key: str = Field(min_length=1, max_length=128, description="Pre-decision buyer context identifier")
    intent: BuyerIntent = Field(description="Extracted buyer intent and constraints")
    commerce_context: Optional[MerchantCommerceContext] = Field(default=None, description="Optional merchant catalog & constraints context")
    candidates: List[PolicyCandidate] = Field(min_length=1, description="Candidate policies generated by Phase 4")
    selection_version: str = Field(default=SELECTION_SCHEMA_VERSION, description="Contract version")
    decision_timestamp: Optional[datetime] = Field(default=None, description="Decision snapshot timestamp")


class PolicySelectionResult(BaseModel):
    """Authoritative decision output of deterministic candidate selection."""
    model_config = ConfigDict(extra="forbid")

    selection_id: str = Field(description="Unique selection outcome ID (sel_...)")
    merchant_id: str = Field(description="Merchant tenant ID")
    opportunity_id: str = Field(description="Canonical opportunity identifier")
    buyer_context_key: str = Field(description="Buyer context key")
    selected_policy_id: str = Field(description="Policy ID chosen by deterministic selection")
    selected_policy_version: str = Field(description="Contract version of the chosen policy")
    baseline_policy_id: str = Field(description="Policy ID of the evaluated NO_OFFER baseline")
    selected_predicted_contribution_paise: int = Field(description="Expected contribution in integer paise of selected policy")
    selected_uncertainty: float = Field(description="Predictive uncertainty of selected policy")
    baseline_predicted_contribution_paise: int = Field(description="Expected contribution in integer paise of NO_OFFER baseline")
    ranked_candidates: List[CandidateSelectionScore] = Field(description="Full ordered candidate slate")
    model_version: str = Field(default="learning-model/v1", description="Phase 8.4 model version")
    feature_version: str = Field(default="feature-schema/v1", description="Phase 8.4 feature version")
    selection_version: str = Field(default=SELECTION_SCHEMA_VERSION, description="Selection contract version")
    selection_reason: str = Field(description="Factual deterministic explanation of the selection decision")
    selection_timestamp: datetime = Field(description="Timestamp when selection was executed")
