"""initial_full_schema

Revision ID: 0db8d2e8f8f1
Revises: 
Create Date: 2026-09-04 01:41:35.089042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db8d2e8f8f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_event_id', sa.String(length=64), nullable=True),
    sa.Column('merchant_id', sa.String(length=64), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('opportunity_id', sa.String(length=128), nullable=True),
    sa.Column('decision_id', sa.String(length=64), nullable=True),
    sa.Column('execution_id', sa.String(length=64), nullable=True),
    sa.Column('outcome_id', sa.String(length=64), nullable=True),
    sa.Column('evidence_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_audit_event_id'), ['audit_event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_audit_events_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_evidence_id'), ['evidence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_outcome_id'), ['outcome_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_request_id'), ['request_id'], unique=False)

    op.create_table('merchants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('business_objective', sa.String(length=64), nullable=False),
    sa.Column('minimum_margin_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('maximum_discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('target_aov_paise', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merchants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchants_status'), ['status'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=True),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('receipt', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_decision_id'), ['decision_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_razorpay_order_id'), ['razorpay_order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_receipt'), ['receipt'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)

    op.create_table('processed_webhook_events',
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('processed_webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processed_webhook_events_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_webhook_events_event_type'), ['event_type'], unique=False)

    op.create_table('canonical_decisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('opportunity_id', sa.String(length=64), nullable=False),
    sa.Column('decision_version', sa.String(length=64), nullable=False),
    sa.Column('buyer_context_key', sa.String(length=255), nullable=False),
    sa.Column('decision_mode', sa.String(length=32), nullable=False),
    sa.Column('decision_reason', sa.String(length=128), nullable=False),
    sa.Column('selected_policy_id', sa.String(length=64), nullable=False),
    sa.Column('selected_strategy_type', sa.String(length=64), nullable=False),
    sa.Column('proposed_price_paise', sa.Integer(), nullable=False),
    sa.Column('predicted_contribution_paise', sa.Integer(), nullable=False),
    sa.Column('decision_envelope_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canonical_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canonical_decisions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_decisions_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index('ix_canonical_decisions_merchant_opp', ['merchant_id', 'opportunity_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_canonical_decisions_opportunity_id'), ['opportunity_id'], unique=False)

    op.create_table('closed_loop_evaluations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('overall_outcome', sa.String(length=32), nullable=False),
    sa.Column('dataset_id', sa.String(length=128), nullable=False),
    sa.Column('baseline_definition_json', sa.JSON(), nullable=False),
    sa.Column('training_definition_json', sa.JSON(), nullable=False),
    sa.Column('evaluation_definition_json', sa.JSON(), nullable=False),
    sa.Column('holdout_definition_json', sa.JSON(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('summary_metrics_json', sa.JSON(), nullable=False),
    sa.Column('learning_curve_json', sa.JSON(), nullable=False),
    sa.Column('holdout_metrics_json', sa.JSON(), nullable=False),
    sa.Column('diagnostics_json', sa.JSON(), nullable=False),
    sa.Column('warnings_json', sa.JSON(), nullable=False),
    sa.Column('failure_reasons_json', sa.JSON(), nullable=False),
    sa.Column('contract_versions_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('closed_loop_evaluations', schema=None) as batch_op:
        batch_op.create_index('ix_closed_loop_eval_merchant_mode', ['merchant_id', 'mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_closed_loop_evaluations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_closed_loop_evaluations_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_closed_loop_evaluations_status'), ['status'], unique=False)

    op.create_table('execution_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('proposal_id', sa.String(length=64), nullable=False),
    sa.Column('candidate_id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=True),
    sa.Column('receipt', sa.String(length=40), nullable=False),
    sa.Column('authorized_amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rejection_reasons', sa.JSON(), nullable=False),
    sa.Column('recalculated_economics', sa.JSON(), nullable=True),
    sa.Column('audit_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_records_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_execution_records_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_records_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_records_proposal_id'), ['proposal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_records_razorpay_order_id'), ['razorpay_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_records_receipt'), ['receipt'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_records_status'), ['status'], unique=False)

    op.create_table('experiments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('control_policy_id', sa.String(length=64), nullable=False),
    sa.Column('treatment_policy_id', sa.String(length=64), nullable=False),
    sa.Column('control_proposal_snapshot', sa.JSON(), nullable=False),
    sa.Column('treatment_proposal_snapshot', sa.JSON(), nullable=False),
    sa.Column('hypothesis', sa.JSON(), nullable=False),
    sa.Column('guardrails', sa.JSON(), nullable=False),
    sa.Column('primary_metric', sa.String(length=64), nullable=False),
    sa.Column('secondary_metrics', sa.JSON(), nullable=False),
    sa.Column('randomization_seed', sa.Integer(), nullable=False),
    sa.Column('assignment_strategy', sa.String(length=32), nullable=False),
    sa.Column('population_scenarios', sa.JSON(), nullable=False),
    sa.Column('policy_diff', sa.JSON(), nullable=True),
    sa.Column('sample_size_target', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_status'), ['status'], unique=False)

    op.create_table('exploration_decision_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('opportunity_id', sa.String(length=128), nullable=False),
    sa.Column('buyer_context_key', sa.String(length=128), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('exploit_policy_id', sa.String(length=64), nullable=False),
    sa.Column('exploit_policy_version', sa.String(length=32), nullable=False),
    sa.Column('selected_policy_id', sa.String(length=64), nullable=False),
    sa.Column('selected_policy_version', sa.String(length=32), nullable=False),
    sa.Column('predicted_contribution_paise', sa.BigInteger(), nullable=False),
    sa.Column('uncertainty', sa.Float(), nullable=False),
    sa.Column('ucb_score_paise', sa.BigInteger(), nullable=False),
    sa.Column('exposure_paise', sa.BigInteger(), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('safety_check_id', sa.String(length=64), nullable=True),
    sa.Column('budget_state_json', sa.JSON(), nullable=False),
    sa.Column('policy_exposure_state_json', sa.JSON(), nullable=False),
    sa.Column('context_exposure_state_json', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.Column('selection_version', sa.String(length=32), nullable=False),
    sa.Column('exploration_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exploration_decision_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exploration_decision_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exploration_decision_records_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exploration_decision_records_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index('ix_policy_exploration_merchant_opp', ['merchant_id', 'opportunity_id'], unique=False)

    op.create_table('merchant_active_policies',
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('policy_id', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('promotion_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    op.create_table('merchant_exploration_states',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('window_id', sa.String(length=64), nullable=False),
    sa.Column('opportunities_used', sa.Integer(), nullable=False),
    sa.Column('exposure_paise_used', sa.BigInteger(), nullable=False),
    sa.Column('consecutive_explorations', sa.Integer(), nullable=False),
    sa.Column('policy_counts_json', sa.JSON(), nullable=False),
    sa.Column('context_counts_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('merchant_exploration_states', schema=None) as batch_op:
        batch_op.create_index('ix_merchant_exploration_state_mw', ['merchant_id', 'window_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_merchant_exploration_states_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchant_exploration_states_merchant_id'), ['merchant_id'], unique=False)

    op.create_table('merchant_policy_version_records',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('policy_id', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('lifecycle_status', sa.String(length=32), nullable=False),
    sa.Column('strategy_type', sa.String(length=32), nullable=False),
    sa.Column('product_ids_json', sa.JSON(), nullable=False),
    sa.Column('incentive_json', sa.JSON(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'policy_id', 'policy_version', name='uq_merchant_policy_version')
    )
    with op.batch_alter_table('merchant_policy_version_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merchant_policy_version_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchant_policy_version_records_lifecycle_status'), ['lifecycle_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchant_policy_version_records_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchant_policy_version_records_policy_id'), ['policy_id'], unique=False)
        batch_op.create_index('ix_merchant_policy_version_status', ['merchant_id', 'lifecycle_status'], unique=False)

    op.create_table('merchant_priorities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('priority_product_ids', sa.JSON(), nullable=False),
    sa.Column('priority_categories', sa.JSON(), nullable=False),
    sa.Column('clearance_product_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('merchant_priorities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merchant_priorities_merchant_id'), ['merchant_id'], unique=True)

    op.create_table('payments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_description', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)

    op.create_table('policy_learning_model_states',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('algorithm_version', sa.String(length=32), nullable=False),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.Column('reward_version', sa.String(length=32), nullable=False),
    sa.Column('formula_version', sa.String(length=32), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('lambda_reg', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('alpha_paise', sa.BigInteger(), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('matrix_a_json', sa.JSON(), nullable=False),
    sa.Column('vector_b_json', sa.JSON(), nullable=False),
    sa.Column('theta_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_learning_model_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_learning_model_states_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_learning_model_states_merchant_id'), ['merchant_id'], unique=True)

    op.create_table('policy_lifecycle_audit_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('transition_type', sa.String(length=32), nullable=False),
    sa.Column('candidate_policy_id', sa.String(length=64), nullable=False),
    sa.Column('candidate_policy_version', sa.String(length=32), nullable=False),
    sa.Column('previous_active_policy_id', sa.String(length=64), nullable=True),
    sa.Column('previous_active_policy_version', sa.String(length=32), nullable=True),
    sa.Column('resulting_active_policy_id', sa.String(length=64), nullable=True),
    sa.Column('resulting_active_policy_version', sa.String(length=32), nullable=True),
    sa.Column('promotion_status', sa.String(length=32), nullable=False),
    sa.Column('eligibility_status', sa.String(length=64), nullable=False),
    sa.Column('failure_codes_json', sa.JSON(), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=True),
    sa.Column('evidence_references_json', sa.JSON(), nullable=False),
    sa.Column('safety_check_id', sa.String(length=64), nullable=True),
    sa.Column('promotion_config_version', sa.String(length=32), nullable=False),
    sa.Column('lifecycle_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_lifecycle_audit_records', schema=None) as batch_op:
        batch_op.create_index('ix_lifecycle_audit_merchant_trans', ['merchant_id', 'transition_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_lifecycle_audit_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_lifecycle_audit_records_merchant_id'), ['merchant_id'], unique=False)

    op.create_table('policy_safety_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('opportunity_id', sa.String(length=128), nullable=False),
    sa.Column('buyer_context_key', sa.String(length=128), nullable=False),
    sa.Column('policy_id', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('selection_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failure_codes_json', sa.JSON(), nullable=False),
    sa.Column('recalculated_economics_json', sa.JSON(), nullable=True),
    sa.Column('validation_reason', sa.String(length=128), nullable=False),
    sa.Column('merchant_context_version', sa.String(length=32), nullable=True),
    sa.Column('safety_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_safety_records', schema=None) as batch_op:
        batch_op.create_index('ix_policy_safety_merchant_opp', ['merchant_id', 'opportunity_id', 'policy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_safety_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_safety_records_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_safety_records_opportunity_id'), ['opportunity_id'], unique=False)

    op.create_table('policy_selection_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('opportunity_id', sa.String(length=128), nullable=False),
    sa.Column('buyer_context_key', sa.String(length=128), nullable=False),
    sa.Column('selected_policy_id', sa.String(length=64), nullable=False),
    sa.Column('selected_policy_version', sa.String(length=32), nullable=False),
    sa.Column('baseline_policy_id', sa.String(length=64), nullable=False),
    sa.Column('selected_predicted_contribution_paise', sa.BigInteger(), nullable=False),
    sa.Column('selected_uncertainty', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('baseline_predicted_contribution_paise', sa.BigInteger(), nullable=False),
    sa.Column('ranked_candidates_json', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.Column('selection_version', sa.String(length=32), nullable=False),
    sa.Column('selection_reason', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_selection_records', schema=None) as batch_op:
        batch_op.create_index('ix_policy_selection_merchant_opp', ['merchant_id', 'opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_selection_records_buyer_context_key'), ['buyer_context_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_selection_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_selection_records_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_selection_records_opportunity_id'), ['opportunity_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('price_paise', sa.BigInteger(), nullable=False),
    sa.Column('cost_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('inventory_quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('cost_paise >= 0', name='chk_cost_non_negative'),
    sa.CheckConstraint('inventory_quantity >= 0', name='chk_inventory_non_negative'),
    sa.CheckConstraint('price_paise > 0', name='chk_price_positive'),
    sa.CheckConstraint('reserved_quantity >= 0', name='chk_reserved_non_negative'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'sku', name='uq_products_merchant_sku')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_merchant_id'), ['merchant_id'], unique=False)

    op.create_table('decision_executions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('opportunity_id', sa.String(length=128), nullable=False),
    sa.Column('authorization_id', sa.String(length=64), nullable=False),
    sa.Column('policy_id', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('state_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('safety_check_id', sa.String(length=64), nullable=True),
    sa.Column('boundary_status', sa.String(length=32), nullable=False),
    sa.Column('execution_record_id', sa.String(length=64), nullable=True),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=True),
    sa.Column('authorized_amount_paise', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rejection_reasons_json', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['canonical_decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['execution_record_id'], ['execution_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decision_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_executions_authorization_id'), ['authorization_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_decision_executions_boundary_status'), ['boundary_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_executions_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_executions_execution_record_id'), ['execution_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_executions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_executions_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index('ix_decision_executions_merchant_decision', ['merchant_id', 'decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_executions_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_executions_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_executions_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_executions_razorpay_order_id'), ['razorpay_order_id'], unique=False)

    op.create_table('observations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('experiment_id', sa.String(length=64), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('variant', sa.String(length=16), nullable=False),
    sa.Column('outcome_type', sa.String(length=32), nullable=False),
    sa.Column('buyer_selection_result_id', sa.String(length=64), nullable=True),
    sa.Column('selected_offer_id', sa.String(length=64), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=True),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=True),
    sa.Column('payment_outcome', sa.String(length=32), nullable=True),
    sa.Column('revenue_paise', sa.BigInteger(), nullable=False),
    sa.Column('contribution_paise', sa.BigInteger(), nullable=False),
    sa.Column('margin_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('guardrail_violations', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['execution_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observations_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_observations_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_variant'), ['variant'], unique=False)

    op.create_table('product_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('primary_product_id', sa.String(length=64), nullable=False),
    sa.Column('related_product_id', sa.String(length=64), nullable=False),
    sa.Column('relationship_type', sa.String(length=32), nullable=False),
    sa.Column('affinity_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('primary_product_id != related_product_id', name='chk_no_self_relationship'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('primary_product_id', 'related_product_id', 'relationship_type', name='uq_product_relationship')
    )
    with op.batch_alter_table('product_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_relationships_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_relationships_primary_product_id'), ['primary_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_relationships_related_product_id'), ['related_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_relationships_relationship_type'), ['relationship_type'], unique=False)

    op.create_table('learning_evidence',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('evidence_version', sa.String(length=32), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('experiment_id', sa.String(length=64), nullable=False),
    sa.Column('experiment_observation_id', sa.String(length=64), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('policy_id', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('variant', sa.String(length=16), nullable=False),
    sa.Column('buyer_context_key', sa.String(length=128), nullable=False),
    sa.Column('buyer_intent_version', sa.String(length=32), nullable=False),
    sa.Column('buyer_selection_result_id', sa.String(length=64), nullable=True),
    sa.Column('simulation_version', sa.String(length=32), nullable=True),
    sa.Column('execution_id', sa.String(length=64), nullable=True),
    sa.Column('provider_order_id', sa.String(length=64), nullable=True),
    sa.Column('verified_payment_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('outcome_type', sa.String(length=32), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('expected_revenue_paise', sa.BigInteger(), nullable=False),
    sa.Column('expected_contribution_paise', sa.BigInteger(), nullable=False),
    sa.Column('observed_revenue_paise', sa.BigInteger(), nullable=True),
    sa.Column('observed_contribution_paise', sa.BigInteger(), nullable=True),
    sa.Column('margin_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('guardrail_results', sa.JSON(), nullable=False),
    sa.Column('evidence_status', sa.String(length=32), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=32), nullable=False),
    sa.Column('learning_eligible', sa.Boolean(), nullable=False),
    sa.Column('eligibility_reasons', sa.JSON(), nullable=False),
    sa.Column('aggregation_key', sa.String(length=256), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['experiment_observation_id'], ['observations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_evidence_aggregation_key'), ['aggregation_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_evidence_buyer_context_key'), ['buyer_context_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_evidence_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_evidence_experiment_observation_id'), ['experiment_observation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_evidence_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_evidence_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_learning_evidence_learning_eligible'), ['learning_eligible'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_evidence_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_evidence_policy_id'), ['policy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_evidence_scenario_id'), ['scenario_id'], unique=False)

    op.create_table('outcome_feedbacks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('opportunity_id', sa.String(length=128), nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('feedback_version', sa.String(length=32), nullable=False),
    sa.Column('transaction_state', sa.String(length=32), nullable=False),
    sa.Column('outcome_status', sa.String(length=32), nullable=False),
    sa.Column('processing_state', sa.String(length=32), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('learning_eligible', sa.Boolean(), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=True),
    sa.Column('memory_id', sa.String(length=64), nullable=True),
    sa.Column('model_updated', sa.Boolean(), nullable=False),
    sa.Column('realized_revenue_paise', sa.BigInteger(), nullable=True),
    sa.Column('realized_cogs_paise', sa.BigInteger(), nullable=True),
    sa.Column('reward_contribution_paise', sa.BigInteger(), nullable=True),
    sa.Column('rejection_reasons_json', sa.JSON(), nullable=False),
    sa.Column('audit_metadata', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['canonical_decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['execution_id'], ['decision_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'execution_id', name='uq_outcome_merchant_execution')
    )
    with op.batch_alter_table('outcome_feedbacks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outcome_feedbacks_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outcome_feedbacks_evidence_id'), ['evidence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outcome_feedbacks_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outcome_feedbacks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outcome_feedbacks_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_outcome_feedbacks_is_terminal'), ['is_terminal'], unique=False)
        batch_op.create_index(batch_op.f('ix_outcome_feedbacks_learning_eligible'), ['learning_eligible'], unique=False)
        batch_op.create_index(batch_op.f('ix_outcome_feedbacks_memory_id'), ['memory_id'], unique=False)
        batch_op.create_index('ix_outcome_feedbacks_merchant_decision', ['merchant_id', 'decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outcome_feedbacks_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index('ix_outcome_feedbacks_merchant_status', ['merchant_id', 'outcome_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_outcome_feedbacks_model_updated'), ['model_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_outcome_feedbacks_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outcome_feedbacks_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outcome_feedbacks_outcome_status'), ['outcome_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_outcome_feedbacks_processing_state'), ['processing_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_outcome_feedbacks_razorpay_order_id'), ['razorpay_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outcome_feedbacks_razorpay_payment_id'), ['razorpay_payment_id'], unique=False)

    op.create_table('applied_model_observations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.Integer(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['learning_evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'evidence_id', name='uq_applied_obs_merchant_evidence')
    )
    with op.batch_alter_table('applied_model_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applied_model_observations_evidence_id'), ['evidence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applied_model_observations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applied_model_observations_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index('ix_applied_obs_merchant_evidence', ['merchant_id', 'evidence_id'], unique=False)

    op.create_table('policy_memory',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('memory_version', sa.String(length=32), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('opportunity_id', sa.String(length=128), nullable=False),
    sa.Column('buyer_context_key', sa.String(length=128), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('policy_id', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('experiment_id', sa.String(length=64), nullable=False),
    sa.Column('experiment_version', sa.String(length=32), nullable=False),
    sa.Column('variant', sa.String(length=16), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_source', sa.String(length=32), nullable=False),
    sa.Column('outcome_type', sa.String(length=32), nullable=False),
    sa.Column('learning_eligible', sa.Boolean(), nullable=False),
    sa.Column('reward_id', sa.String(length=64), nullable=False),
    sa.Column('reward_version', sa.String(length=32), nullable=False),
    sa.Column('formula_version', sa.String(length=32), nullable=False),
    sa.Column('reward_state', sa.String(length=32), nullable=False),
    sa.Column('is_admissible', sa.Boolean(), nullable=False),
    sa.Column('is_safety_violation', sa.Boolean(), nullable=False),
    sa.Column('realized_revenue_paise', sa.BigInteger(), nullable=False),
    sa.Column('realized_cogs_paise', sa.BigInteger(), nullable=False),
    sa.Column('realized_discount_paise', sa.BigInteger(), nullable=False),
    sa.Column('reward_contribution_paise', sa.BigInteger(), nullable=False),
    sa.Column('margin_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('superseded_by', sa.String(length=64), nullable=True),
    sa.Column('supersedes', sa.String(length=64), nullable=True),
    sa.Column('correction_reason', sa.String(length=128), nullable=True),
    sa.Column('reconciliation_ref', sa.String(length=128), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('persisted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['learning_evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_memory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_memory_buyer_context_key'), ['buyer_context_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_memory_evidence_id'), ['evidence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_memory_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_memory_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_memory_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_policy_memory_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_memory_learning_eligible'), ['learning_eligible'], unique=False)
        batch_op.create_index('ix_policy_memory_merchant_context', ['merchant_id', 'buyer_context_key'], unique=False)
        batch_op.create_index('ix_policy_memory_merchant_exp', ['merchant_id', 'experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_memory_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index('ix_policy_memory_merchant_obs_time', ['merchant_id', 'observed_at'], unique=False)
        batch_op.create_index('ix_policy_memory_merchant_opp_current', ['merchant_id', 'opportunity_id', 'is_current'], unique=False)
        batch_op.create_index('ix_policy_memory_merchant_pol_ctx', ['merchant_id', 'policy_id', 'buyer_context_key'], unique=False)
        batch_op.create_index('ix_policy_memory_merchant_policy', ['merchant_id', 'policy_id'], unique=False)
        batch_op.create_index('ix_policy_memory_merchant_policy_ver', ['merchant_id', 'policy_id', 'policy_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_memory_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_memory_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_memory_policy_id'), ['policy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_memory_policy_version'), ['policy_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_memory_reward_id'), ['reward_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_memory_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_memory_superseded_by'), ['superseded_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_memory_supersedes'), ['supersedes'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy_memory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_memory_supersedes'))
        batch_op.drop_index(batch_op.f('ix_policy_memory_superseded_by'))
        batch_op.drop_index(batch_op.f('ix_policy_memory_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_policy_memory_reward_id'))
        batch_op.drop_index(batch_op.f('ix_policy_memory_policy_version'))
        batch_op.drop_index(batch_op.f('ix_policy_memory_policy_id'))
        batch_op.drop_index(batch_op.f('ix_policy_memory_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_policy_memory_observed_at'))
        batch_op.drop_index('ix_policy_memory_merchant_policy_ver')
        batch_op.drop_index('ix_policy_memory_merchant_policy')
        batch_op.drop_index('ix_policy_memory_merchant_pol_ctx')
        batch_op.drop_index('ix_policy_memory_merchant_opp_current')
        batch_op.drop_index('ix_policy_memory_merchant_obs_time')
        batch_op.drop_index(batch_op.f('ix_policy_memory_merchant_id'))
        batch_op.drop_index('ix_policy_memory_merchant_exp')
        batch_op.drop_index('ix_policy_memory_merchant_context')
        batch_op.drop_index(batch_op.f('ix_policy_memory_learning_eligible'))
        batch_op.drop_index(batch_op.f('ix_policy_memory_is_current'))
        batch_op.drop_index(batch_op.f('ix_policy_memory_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_policy_memory_id'))
        batch_op.drop_index(batch_op.f('ix_policy_memory_experiment_id'))
        batch_op.drop_index(batch_op.f('ix_policy_memory_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_policy_memory_buyer_context_key'))

    op.drop_table('policy_memory')
    with op.batch_alter_table('applied_model_observations', schema=None) as batch_op:
        batch_op.drop_index('ix_applied_obs_merchant_evidence')
        batch_op.drop_index(batch_op.f('ix_applied_model_observations_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_applied_model_observations_id'))
        batch_op.drop_index(batch_op.f('ix_applied_model_observations_evidence_id'))

    op.drop_table('applied_model_observations')
    with op.batch_alter_table('outcome_feedbacks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outcome_feedbacks_razorpay_payment_id'))
        batch_op.drop_index(batch_op.f('ix_outcome_feedbacks_razorpay_order_id'))
        batch_op.drop_index(batch_op.f('ix_outcome_feedbacks_processing_state'))
        batch_op.drop_index(batch_op.f('ix_outcome_feedbacks_outcome_status'))
        batch_op.drop_index(batch_op.f('ix_outcome_feedbacks_order_id'))
        batch_op.drop_index(batch_op.f('ix_outcome_feedbacks_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_outcome_feedbacks_model_updated'))
        batch_op.drop_index('ix_outcome_feedbacks_merchant_status')
        batch_op.drop_index(batch_op.f('ix_outcome_feedbacks_merchant_id'))
        batch_op.drop_index('ix_outcome_feedbacks_merchant_decision')
        batch_op.drop_index(batch_op.f('ix_outcome_feedbacks_memory_id'))
        batch_op.drop_index(batch_op.f('ix_outcome_feedbacks_learning_eligible'))
        batch_op.drop_index(batch_op.f('ix_outcome_feedbacks_is_terminal'))
        batch_op.drop_index(batch_op.f('ix_outcome_feedbacks_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_outcome_feedbacks_id'))
        batch_op.drop_index(batch_op.f('ix_outcome_feedbacks_execution_id'))
        batch_op.drop_index(batch_op.f('ix_outcome_feedbacks_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_outcome_feedbacks_decision_id'))

    op.drop_table('outcome_feedbacks')
    with op.batch_alter_table('learning_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_evidence_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_learning_evidence_policy_id'))
        batch_op.drop_index(batch_op.f('ix_learning_evidence_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_learning_evidence_learning_eligible'))
        batch_op.drop_index(batch_op.f('ix_learning_evidence_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_learning_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_learning_evidence_experiment_observation_id'))
        batch_op.drop_index(batch_op.f('ix_learning_evidence_experiment_id'))
        batch_op.drop_index(batch_op.f('ix_learning_evidence_buyer_context_key'))
        batch_op.drop_index(batch_op.f('ix_learning_evidence_aggregation_key'))

    op.drop_table('learning_evidence')
    with op.batch_alter_table('product_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_relationships_relationship_type'))
        batch_op.drop_index(batch_op.f('ix_product_relationships_related_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_relationships_primary_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_relationships_merchant_id'))

    op.drop_table('product_relationships')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_variant'))
        batch_op.drop_index(batch_op.f('ix_observations_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_observations_order_id'))
        batch_op.drop_index(batch_op.f('ix_observations_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_observations_id'))
        batch_op.drop_index(batch_op.f('ix_observations_experiment_id'))
        batch_op.drop_index(batch_op.f('ix_observations_execution_id'))

    op.drop_table('observations')
    with op.batch_alter_table('decision_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_executions_razorpay_order_id'))
        batch_op.drop_index(batch_op.f('ix_decision_executions_order_id'))
        batch_op.drop_index(batch_op.f('ix_decision_executions_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_decision_executions_merchant_id'))
        batch_op.drop_index('ix_decision_executions_merchant_decision')
        batch_op.drop_index(batch_op.f('ix_decision_executions_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_decision_executions_id'))
        batch_op.drop_index(batch_op.f('ix_decision_executions_execution_record_id'))
        batch_op.drop_index(batch_op.f('ix_decision_executions_decision_id'))
        batch_op.drop_index(batch_op.f('ix_decision_executions_boundary_status'))
        batch_op.drop_index(batch_op.f('ix_decision_executions_authorization_id'))

    op.drop_table('decision_executions')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_products_is_active'))
        batch_op.drop_index(batch_op.f('ix_products_id'))
        batch_op.drop_index(batch_op.f('ix_products_category'))

    op.drop_table('products')
    with op.batch_alter_table('policy_selection_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_selection_records_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_policy_selection_records_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_policy_selection_records_id'))
        batch_op.drop_index(batch_op.f('ix_policy_selection_records_buyer_context_key'))
        batch_op.drop_index('ix_policy_selection_merchant_opp')

    op.drop_table('policy_selection_records')
    with op.batch_alter_table('policy_safety_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_safety_records_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_policy_safety_records_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_policy_safety_records_id'))
        batch_op.drop_index('ix_policy_safety_merchant_opp')

    op.drop_table('policy_safety_records')
    with op.batch_alter_table('policy_lifecycle_audit_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_lifecycle_audit_records_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_policy_lifecycle_audit_records_id'))
        batch_op.drop_index('ix_lifecycle_audit_merchant_trans')

    op.drop_table('policy_lifecycle_audit_records')
    with op.batch_alter_table('policy_learning_model_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_learning_model_states_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_policy_learning_model_states_id'))

    op.drop_table('policy_learning_model_states')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))
        batch_op.drop_index(batch_op.f('ix_payments_id'))

    op.drop_table('payments')
    with op.batch_alter_table('merchant_priorities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchant_priorities_merchant_id'))

    op.drop_table('merchant_priorities')
    with op.batch_alter_table('merchant_policy_version_records', schema=None) as batch_op:
        batch_op.drop_index('ix_merchant_policy_version_status')
        batch_op.drop_index(batch_op.f('ix_merchant_policy_version_records_policy_id'))
        batch_op.drop_index(batch_op.f('ix_merchant_policy_version_records_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_merchant_policy_version_records_lifecycle_status'))
        batch_op.drop_index(batch_op.f('ix_merchant_policy_version_records_id'))

    op.drop_table('merchant_policy_version_records')
    with op.batch_alter_table('merchant_exploration_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchant_exploration_states_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_merchant_exploration_states_id'))
        batch_op.drop_index('ix_merchant_exploration_state_mw')

    op.drop_table('merchant_exploration_states')
    op.drop_table('merchant_active_policies')
    with op.batch_alter_table('exploration_decision_records', schema=None) as batch_op:
        batch_op.drop_index('ix_policy_exploration_merchant_opp')
        batch_op.drop_index(batch_op.f('ix_exploration_decision_records_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_exploration_decision_records_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_exploration_decision_records_id'))

    op.drop_table('exploration_decision_records')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiments_status'))
        batch_op.drop_index(batch_op.f('ix_experiments_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_experiments_id'))

    op.drop_table('experiments')
    with op.batch_alter_table('execution_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_records_status'))
        batch_op.drop_index(batch_op.f('ix_execution_records_receipt'))
        batch_op.drop_index(batch_op.f('ix_execution_records_razorpay_order_id'))
        batch_op.drop_index(batch_op.f('ix_execution_records_proposal_id'))
        batch_op.drop_index(batch_op.f('ix_execution_records_order_id'))
        batch_op.drop_index(batch_op.f('ix_execution_records_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_execution_records_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_execution_records_id'))

    op.drop_table('execution_records')
    with op.batch_alter_table('closed_loop_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_closed_loop_evaluations_status'))
        batch_op.drop_index(batch_op.f('ix_closed_loop_evaluations_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_closed_loop_evaluations_id'))
        batch_op.drop_index('ix_closed_loop_eval_merchant_mode')

    op.drop_table('closed_loop_evaluations')
    with op.batch_alter_table('canonical_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canonical_decisions_opportunity_id'))
        batch_op.drop_index('ix_canonical_decisions_merchant_opp')
        batch_op.drop_index(batch_op.f('ix_canonical_decisions_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_canonical_decisions_id'))

    op.drop_table('canonical_decisions')
    with op.batch_alter_table('processed_webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processed_webhook_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_processed_webhook_events_event_id'))

    op.drop_table('processed_webhook_events')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_receipt'))
        batch_op.drop_index(batch_op.f('ix_orders_razorpay_order_id'))
        batch_op.drop_index(batch_op.f('ix_orders_id'))
        batch_op.drop_index(batch_op.f('ix_orders_decision_id'))

    op.drop_table('orders')
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchants_status'))
        batch_op.drop_index(batch_op.f('ix_merchants_id'))

    op.drop_table('merchants')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_outcome_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_execution_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_decision_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_audit_event_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
